sonar.projectKey=gudge25_live-ai_dc9090aa-e949-4be5-b28a-faa8712b6f0a
sonar.javascript.lcov.reportPaths=packages/shared/coverage/lcov.info,apps/server/coverage/lcov.info,apps/extension/coverage/lcov.info
